services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - HISTFILE=/usr/src/app/log/.bash_history
    links:
      - db
      - redis
      - sidekiq
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      minio:
        condition: service_healthy

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres
      interval: 2s
      timeout: 5s
      retries: 30

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  sidekiq:
    build: .
    command: bundle exec sidekiq
    depends_on:
      - redis
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
  
  minio:
    # for S3 simulation
    image: quay.io/minio/minio:latest
    restart: unless-stopped
    healthcheck:
      test: "(touch /data/.mounted && curl -f http://minio:9000/minio/health/live) || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - s3_data:/data
    environment:
      - MINIO_ROOT_USER=aws_local
      - MINIO_ROOT_PASSWORD=aws_pass
    command: server /data --console-address ":9001"

volumes:
  pg_data:
  redis_data:
  bundle:
  s3_data:
